### ISSUE TITLE
add the migrations to the repo

### ISSUE THREAD

**Issue by stdweird** [heliumdatacommons/auth_microservice#17]
without the migrations as part of the code, we can't distribute or unittest the repo. shipping the migrations is a common thing to do and provides an easy upgrade path for the users.

**Comment by stdweird** [comment]
@theferrit32 https://github.com/heliumdatacommons/auth_microservice/commit/5ef30a50159bb9f9234abe04227e3a5785da9b4c adds 2 migration files. what is the second one for? the first one alone looks complete (it's identical to one i generated from scratch)

**Comment by theferrit32** [comment]
@stdweird I think the 0002 one was incorrectly added and is redundant.  I will regenerate and verify that this is the case, and remove it if so.

**Comment by theferrit32** [comment]
@stdweird I pushed an update, let me know if this does not work for your packaging efforts

**Comment by stdweird** [comment]
@theferrit32 thanks. looks ok again now
can you enable travis for this repo too? (i can't do this myself since i have no write rights)
