### ISSUE TITLE
User uniqueness should include provider

### ISSUE THREAD

**Issue by stdweird** [heliumdatacommons/auth_microservice#20]
The current User model (not the code to create/lookup users) does not take into account what provider the user comes from.

This might cause issues, because we would like to test with a production and a qa idp, but the contain (almost) identical user data, and thus there are overlaps (and we already had 
```
duplicate key value violates unique constraint "token_service_user_user_name_key"
```
errors

I'm not sure how to proceed, but ideally a new row for provider is added to the user model (and the uniqueness is extended to user_name/id/provider combo (or id/provider) instead of only username

**Comment by theferrit32** [comment]
I wrote that code under the assumption that user names had domains attached which would make them unique by pinning to IDPs.  I don't see an issue with also including the provider in the user table primary key set, and that may be something which is needed down the line anyways for when I start adding additional providers to my deployment which have potentially overlapping name spaces.
